packageExtensions:
  "@nestjs/common@*":
    dependencies:
      "@grpc/proto-loader": "*"
      cache-manager: "*"
      reflect-metadata: "*"
      rxjs: "*"
  "@nestjs/core@*":
    dependencies:
      "@nestjs/platform-express": "*"
      "@nestjs/websockets": "*"
      reflect-metadata: "*"
      rxjs: "*"
  "@nestjs/cqrs@*":
    dependencies:
      reflect-metadata: "*"
      rxjs: "*"
  "@nestjs/microservices@*":
    dependencies:
      "@grpc/grpc-js": "*"
      "@grpc/proto-loader": "*"
      "@nestjs/websockets": "*"
      amqp-connection-manager: "*"
      amqplib: "*"
      kafkajs: "*"
      mqtt: "*"
      nats: "*"
      redis: "*"
      reflect-metadata: "*"
      rxjs: "*"
  "@nestjs/passport@*":
    dependencies:
      passport: "*"
  "@nestjs/typeorm@*":
    dependencies:
      rxjs: "*"
  "@nestjs/websockets@*":
    dependencies:
      "@nestjs/platform-socket.io": "*"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
